### ISSUE TITLE
everything is ripped

### ISSUE THREAD

**Issue by Leoreal1119** [developer9998/GorillaLocoPlus#2]
1. player script is ripped and you prob used chat gpt plus to try to make it look like its not but you can still see the chat gpt a little

2. the stone hit sound but you may of got it from the website what gtag got it from so i wont go into that

3. the ice sound i have never seen on the website they use as ik what one they use so you prob ripped that

4. i think the slide as if you make it shorter it looks just like gtag's slide but i don't really know if you ripped it but it does look like it

idc that your a gtag mod creator that does not give you the right to rip gtag take there code and 2 hit sounds and make them public for everyone to use mod creators dont do that so stop saying that as a excuse i started to laugh with one of my friends when i saw what you said to him in the other issue
also your colliders are broken in the project change them to mesh colliders if you keep this up after all the hate your gonna get from giving everyone gtag's assets
and everything is one hitsound so you did not even rip it right or chatgpt removed it being more then one and material based

**Comment by developer9998** [comment]
GorillaLocomotion is an existing-public repository here on GitHub, which I have updated appropriately to better fit the gameplay and mechanics in Gorilla Tag. 

In addition, the "slip" sound can be found on Freesound, not every sound Lemming used was dragged and dropped into the game, some care was put into the sounds to make them loop better.

No usage of AI was used to modify the code, I just know what I'm doing and you don't even know how to make a good point.
