### ISSUE TITLE
Ripped

### ISSUE THREAD

**Issue by Leoreal1119** [developer9998/GorillaLocoPlus#3]
sure you deleted my last one and made a point that the ice sound is a asset from freesound
but i have gtag's player script as a friend gave it to me for proof that this is ripped and your "edited" player script is just gtag's shortened down its the same
and you did not even rip it right as the hit sounds spam

don't use i am a mod creator as a excuse
its still ripped anyone who knows gtags player code will know
the more you delete this i will make more

**Comment by developer9998** [comment]
I've already stated what I have needed to state. Quit making lies, cut it out
