### ISSUE TITLE
RIPPED

### ISSUE THREAD

**Issue by Leoreal1119** [developer9998/GorillaLocoPlus#4]
sure you deleted my last one and made a point that the ice sound is a asset from freesound
but i have gtag's player script as a friend gave it to me for proof that this is ripped and your "edited" player script is just gtag's shortened down its the same
and you did not even rip it right as the hit sounds spam

don't use i am a mod creator as a excuse
its still ripped anyone who knows gtags player code will know
the more you delete this i will make more
i wont stop lmao its not updated its ripped and edited a little

**Comment by developer9998** [comment]
I didn't delete anything, you just lack the fundamentals of GitHub.

**Comment by developer9998** [comment]
You're making it worse by copy and pasting issues lmao, grow up kiddo
